steps:
  # 🧩 Step 1: Clone your GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'clone'
      - 'https://github.com/saisairepo/brangay.git'

  # 🏗️ Step 2: Build Docker image from the cloned repo folder
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'brangay/Dockerfile'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/ml-sandbox-project/error/error:latest'
      - 'brangay'

  # 🚀 Step 3: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/ml-sandbox-project/error/error:latest'

images:
  - 'asia-southeast1-docker.pkg.dev/ml-sandbox-project/error/error:latest'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
